[template]
src = "elasticsearch.yml.tmpl"
dest = "/elasticsearch/config/elasticsearch.yml"
keys = [
    "CLUSTER_NAME",
    "NODE_NAME",
    "NODE_MASTER",
    "NODE_DATA",
    "DISCOVERY_HOSTS",
    "MINIMUM_MASTER_NODES",
    "NETWORK_PUBLISH_HOST",
    "ES_HEAP_SIZE"
]